# action.yml
name: 'Binoc Bot'
description: 'Binoc is a GitHub Actions Workflow that can update package build instructions in GitHub Repositories.'
inputs:
  repo_path:
    description: 'Location of the Package Build Instructions'
    required: false
    default: '/'
  git_name:
    description: 'Name used within Git for the commits'
    required: false
    default: 'Binoc'
  git_email:
    description: 'Email used within Git for the commits'
    required: false
    default: 'github-action@users.noreply.github.com'
  git_username:
    description: 'Username used within Git for pushing commits'
    required: false
    default: 'actions-user'
  git_token:
    description: 'Token used for authenticating with the upstream repository'
    required: true
  parsers_loaded:
    description: 'Parsing Libraries Enabled'
    required: false
    default: 'spack'
  pr_skip:
    description: "Skip checking out branches, commits, and pull requests."
    required: false
    default: 'false'
  general_action:
    description: 'Tells Binoc if it is running as a GitHub action or not.'
    required: false
    default: 'true'
  branch_prefix:
    description: 'Tells Binoc what prefix to use when creating branches.'
    required: false
    default: 'binoc/'
  repo_spackupstreamlink:
    description: 'Tells Binoc where to look for upstream spack package updates.'
    required: false
    default: ''
  repo_upstreamonly:
    description: 'Tells Binoc whether to just solely check for updates from the defined upstream link'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/autamus/binoc:latest'

branding:
  icon: 'activity'
  color: 'white'
